



export const allUsers = async (req, res, next) => {
    try {
        
    } catch (error) {
        console.log(error)
    }
}